/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package midas.carbon;

import org.junit.jupiter.api.Test;

class MidasCarbonTest {
    @Test
    void appHasAGreeting() {
    }
}
